import type { MetricDefinition } from './model.js';

/**
 * Metric definitions included in every report (JSON and a Markdown appendix).
 * They document grain, formula, and additivity so a reader can check each
 * number. `primaryEvent` is the configured primary conversion event name (or
 * null when none is configured); it is never hardcoded.
 */
export function metricDefinitions(primaryEvent: string | null): MetricDefinition[] {
  const ev = primaryEvent ?? '<primary event>';
  return [
    {
      id: 'gsc.clicks',
      name: 'Search Console clicks (property total)',
      definition: 'Clicks from Google Search results for the property and search type, aggregationType byProperty, summed over complete (final) days in the period. Dates follow Search Console reporting days (America/Los_Angeles).',
      formula: 'SUM(clicks) over gsc_property_daily_current rows with is_final = 1',
      source: 'gsc',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'gsc.impressions',
      name: 'Search Console impressions (property total)',
      definition: 'Impressions for the property and search type (byProperty), summed over complete days. Not additive with page or query rows.',
      formula: 'SUM(impressions) over gsc_property_daily_current rows with is_final = 1',
      source: 'gsc',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'gsc.ctr',
      name: 'Click-through rate',
      definition: 'Computed from summed counts. Never an average of daily or per-row CTR percentages.',
      formula: 'SUM(clicks) / SUM(impressions)',
      source: 'derived',
      additivity: 'non_additive',
      unit: 'ratio',
    },
    {
      id: 'gsc.position',
      name: 'Average position (impression-weighted)',
      definition: 'Impression-weighted mean of reported average positions across compatible rows (same property, search type, and aggregation). An aggregate, not a live ranking.',
      formula: 'SUM(position * impressions) / SUM(impressions)',
      source: 'derived',
      additivity: 'non_additive',
      unit: 'position',
    },
    {
      id: 'gsc.page',
      name: 'Search Console page totals (byPage)',
      definition: 'Per-page clicks/impressions (aggregationType byPage) from gsc_page_daily_current without optional dimensions. Page rows are NOT additive with property totals and are shown top-N only.',
      source: 'gsc',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'gsc.query.visible',
      name: 'Visible query rows',
      definition: 'Page/query detail for targeted pages. Anonymized queries are omitted and row limits apply, so visible query rows never equal page or site totals.',
      source: 'gsc',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'gsc.query.unattributed',
      name: 'Unattributed clicks estimate',
      definition: 'For pages with query detail: page-total clicks minus the sum of visible query-row clicks. An estimate of anonymized plus row-limited traffic.',
      formula: 'SUM(page clicks) - SUM(visible query clicks), same pages and days',
      source: 'derived',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'gsc.segment',
      name: 'Country/device context (byPage rows)',
      definition: 'Page rows requested with country and/or device dimensions, aggregated over a single consistent segment shape. Impressions are counted per page, so these are context, not property totals.',
      source: 'gsc',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'ga4.sessions.google_organic',
      name: 'GA4 Google organic sessions',
      definition: 'Sessions whose session-scoped source is google and medium is organic (session acquisition dimensions). Closest GA4 comparison to Search Console clicks, but not identical.',
      formula: 'SUM(sessions) over ga4_landing_daily_current (channel_view = google_organic, segment_key = \'\', is_complete = 1)',
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'ga4.sessions.all_organic',
      name: 'GA4 all organic-search sessions',
      definition: 'Sessions whose session default channel group is Organic Search (all search engines). Broader business view; never combined with the Google organic view.',
      formula: 'SUM(sessions) over ga4_landing_daily_current (channel_view = all_organic, segment_key = \'\', is_complete = 1)',
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'ga4.engaged_sessions',
      name: 'Engaged sessions',
      definition: 'GA4 engagedSessions for the same channel view. Missing values are reported as incomplete, never as zero.',
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'ga4.key_events',
      name: 'Key events (any key event, occurrences)',
      definition: 'GA4 keyEvents: occurrences of any key event. Repeatable; not sessions or users.',
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'ga4.primary_event.occurrences',
      name: `Primary event occurrences (${ev})`,
      definition: `Occurrences of the configured primary key event "${ev}". Repeatable: one session can trigger it several times. Never divided by sessions.`,
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'ga4.primary_event.session_rate',
      name: `Session key-event rate (${ev})`,
      definition: `GA4 sessionKeyEventRate:${ev}: share of sessions in which the primary event was triggered. Uses the period-level API value when fetched; otherwise the session-weighted aggregate of complete daily values. Never "any key event" unless explicitly labeled as an alternative. GA4 does not document whether the rate is 0-1 or 0-100: a value stored with scale "undetermined" is shown only as an unverified raw value (INFERRED), never as a measured percentage, and is never multiplied by sessions. The scale is established by a value above 1, by the owner (\`sync ga4 --confirm-rate-scale fraction|percent --evidence ... --as "<your name>"\`, a named human's audited assertion), or by the integer consistency of small daily rows; stored rates are then re-marked, older days included.`,
      formula: 'period value, or SUM(rate_d * sessions_d) / SUM(sessions_d) over rows with observed rates',
      source: 'ga4',
      additivity: 'non_additive',
      unit: 'ratio',
    },
    {
      id: 'ga4.primary_event.sessions',
      name: `Sessions with the primary event (${ev})`,
      definition: 'Derived count of sessions that triggered the primary event: daily session key-event rate multiplied by daily sessions, summed. Not event occurrences.',
      formula: 'SUM(rate_d * sessions_d)',
      source: 'derived',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'ga4.primary_event.users',
      name: `Users who triggered the primary event (${ev})`,
      definition: `Period-level share of users who triggered the primary key event (GA4 userKeyEventRate:${ev}) and, when that rate's scale is verified and totalUsers was fetched for exactly the same period and view, the derived user count. Never summed across days or segments. Distinct from event occurrences, sessions that triggered the event, and the session key-event rate.`,
      formula: `userKeyEventRate:${ev} x totalUsers (same period, same channel view)`,
      source: 'derived',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'ga4.session_rate.any',
      name: 'Session key-event rate (any key event)',
      definition: 'GA4 sessionKeyEventRate without an event suffix: share of sessions with ANY key event. Shown only as an explicitly labeled alternative when the primary-event rate is unavailable.',
      source: 'ga4',
      additivity: 'non_additive',
      unit: 'ratio',
    },
    {
      id: 'ga4.users',
      name: 'Users (period level)',
      definition: 'Distinct users fetched at period grain (ga4_period_metrics). Users are not additive across days or segments and are never summed from daily rows.',
      source: 'ga4',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'ga4.revenue',
      name: 'Revenue (source currency)',
      definition: 'Revenue as reported by GA4 in the property currency (integer micros). Kept separate from USD API costs. Never summed across currencies.',
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'currency_micros',
    },
    {
      id: 'ga4.not_set',
      name: '(not set) landing page sessions',
      definition: 'Sessions whose landing page is "(not set)" (for example sessions without a page_view). Kept explicit, not dropped.',
      source: 'ga4',
      additivity: 'across_dates_only',
      unit: 'count',
    },
    {
      id: 'spend.actual',
      name: 'Actual spend',
      definition: 'Reconciled spend in USD micros for the budget month: the provider-reported part plus the part computed from usage (shown separately; see spend.computed).',
      formula: 'provider-reported + computed from usage',
      source: 'budgets',
      additivity: 'additive',
      unit: 'usd_micros',
    },
    {
      id: 'spend.computed',
      name: 'Computed spend (usage x list price)',
      definition: 'Part of the actual spend computed by this application from usage at list price because the provider reported no charge. Not provider-reported; it counts toward the limits, and the provider bill may differ.',
      source: 'budgets',
      additivity: 'additive',
      unit: 'usd_micros',
    },
    {
      id: 'spend.reserved',
      name: 'Reserved spend',
      definition: 'Outstanding reservations (conservative upper-bound estimates) not yet reconciled, including unresolved charges.',
      source: 'budgets',
      additivity: 'additive',
      unit: 'usd_micros',
    },
    {
      id: 'spend.estimated',
      name: 'Estimated-only spend',
      definition: 'Reconciled reservations whose provider did not report an actual amount; counted at the estimate.',
      source: 'budgets',
      additivity: 'additive',
      unit: 'usd_micros',
    },
    {
      id: 'spend.unknown',
      name: 'Unknown charges',
      definition: 'Count of charges whose amount is unknown. They stay reserved at their estimate and are never reported as $0.',
      source: 'budgets',
      additivity: 'additive',
      unit: 'count',
    },
    {
      id: 'spend.remaining',
      name: 'Remaining budget',
      definition: 'Configured monthly ceiling minus committed spend (actual + reserved + estimated-only). A ceiling, not a price quote.',
      source: 'budgets',
      additivity: 'non_additive',
      unit: 'usd_micros',
    },
    {
      id: 'experiments.observation_days',
      name: 'Observation days',
      definition: 'Days since the recorded implementation/observation start (approval or draft creation never starts the window).',
      source: 'experiments',
      additivity: 'non_additive',
      unit: 'days',
    },
    {
      id: 'experiments.enough_evidence',
      name: 'Enough evidence to evaluate',
      definition: 'True only when the minimum observation period has elapsed and the recorded sample requirements (impressions/sessions since start) are met. Before/after comparisons remain observational, not causal.',
      source: 'experiments',
      additivity: 'non_additive',
      unit: 'level',
    },
    {
      id: 'confidence.level',
      name: 'Evidence confidence',
      definition: 'Deterministic assessment from data coverage, completeness, access issues, and synthetic data. high/medium/low/none.',
      source: 'derived',
      additivity: 'non_additive',
      unit: 'level',
    },
    {
      id: 'ai.citations',
      name: 'AI-citation checks',
      definition: 'Grounded AI-search checks: a brand mention is not a citation, a citation is not a click, and a click is not a conversion. Ungrounded model responses are never treated as live search measurements.',
      source: 'ai_citations',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'content.cohort',
      name: 'Published-content cohort performance',
      definition: 'Pages published in the same month (actual implementation date), with byPage Search Console clicks/impressions and GA4 Google organic sessions in the report period.',
      source: 'content',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'links.inbound_internal',
      name: 'Inbound internal links (one crawl)',
      definition: 'Distinct crawled pages observed linking to a page in ONE own-site crawl. A potential orphan has none among the pages a completed crawl fetched; after a partial crawl orphan status is not assessable. An observation of crawl coverage, never an authority score.',
      source: 'crawl',
      additivity: 'non_additive',
      unit: 'count',
    },
    {
      id: 'aeo.heuristic_checks',
      name: 'Page-level AEO checks (heuristic)',
      definition: 'Deterministic editorial checks over stored crawl text (src/crawler/aeo.ts): a direct answer near the top for the page\'s top visible Search Console queries, descriptive headings, self-contained sections, evidence signals, and crawl/index/snippet eligibility from observed directives. Each is ok, review, or unknown. Not ranking rules and not a prediction of AI citations; factual consistency is not assessed.',
      source: 'crawl',
      additivity: 'non_additive',
      unit: 'level',
    },
  ];
}
